### ISSUE TITLE
KEYA and KEYB?

### ISSUE THREAD

**Issue by ScrumpyJack** [ef-gy/rpi-ups-pico#1]
This is very cool. I don't like the python dependancy either.
How do you feel about adding the ability to listen to changes in the 0x69 0x09 and 0x0A registars (KEYA and KEYB) and take action (void)system("whatever"); on keypress?

Like the tor gateway btw :+1:

**Comment by EffinMaggie** [comment]
Heya,

That sounds like a great idea, but I think that'd be better suited for a separate daemon. If for no other reason than that that doesn't really need root access to run - the i2c control interfaces work perfectly fine as unprivileged users with the right group set :).

So I'd think it'd make the most sense to create a userspace-controlled HID device for this. It should be possible to bind that to arbitrary actions pretty easily... I'll look into that over the weekend.

And cheers about the tor gateway - seemed like the perfect use for the little bugger ;).

**Comment by EffinMaggie** [comment]
I think I got the code for this sorted, but I left my Pi out of reach for the weekend.
Gonna take it for a spin tomorrow, see what happens :).

**Comment by EffinMaggie** [comment]
... and it works like a charm. Added documentation and everything.

Enjoy and let me know if you need anything else :).

**Comment by ScrumpyJack** [comment]
I'll give it a shot one evening this week. Hopefully tonight
