### ISSUE TITLE
Setting up GPIO pins fails randomly

### ISSUE THREAD

**Issue by renne** [ef-gy/rpi-ups-pico#12]
When picod is started it randomly exits with
`Could not set up pin #22 as an output pin for the pulse train.`
or
`Could not set up pin #27 as input for the FSSD feature.`

Just wait 100 ms between exporting a GPIO and doing anything else on it. ;-)

**Comment by EffinMaggie** [comment]
Hey, thanks for reporting!

Hmmm, I'd really hate to wait for something like 100ms with no reason. Maybe I should just retry a few times with an exponential backoff instead...

What hardware are you using with the pico?

**Comment by renne** [comment]
There is some random delay when the kernel creates the GPIO-sysfs file-descriptors in /dev. If you try to access them directly after the export/creation it can happen that they do not exists, yet. Waiting 100 ms solves this problem. You don't have to wait 100 ms in the loop but only once after exporting. ;-)

The hardware is a Raspberry Pi 2B with the UPS Pico HV3.0A and the [Homematic module](https://www.elv.de/homematic-funkmodul-fuer-raspberry-pi-bausatz.html). I also tested without the Homematic module.

**Comment by EffinMaggie** [comment]
Thanks!

Turns out that I've only tested this with a Pi 2B and a Pi 3 with a pre-V3 Pico board, which is probably the important change here :).
I'll do the exponential backoff between creating the export and checking if it succeeded. That way it'll not wait too long in most cases and should still back off to a similar amount of time.

**Comment by EffinMaggie** [comment]
@renne can you give this a shot to see if it fixes the setup problem?

**Comment by renne** [comment]
The exponential backoff algorithm works!

**Comment by EffinMaggie** [comment]
Nice, I'll mark this as fixed then :).
