### ISSUE TITLE
Feedback: pico-i2cd

### ISSUE THREAD

**Issue by ScrumpyJack** [ef-gy/rpi-ups-pico#2]
pico-i2cd works perfectly for me, and thd is a happy bunny on keypress.
Tested with the colored leds on the PIco:
BTN_A   1       i2cset -y 1 0x6b 0x0d 0x01
BTN_A   0       i2cset -y 1 0x6b 0x0d 0x00
BTN_B   1       i2cset -y 1 0x6b 0x0c 0x01
BTN_B   0       i2cset -y 1 0x6b 0x0c 0x00

**Comment by EffinMaggie** [comment]
Sweet!

That does remind me that it'd be nice to hook up the LEDs so they can be controlled through the input driver... :)
