### ISSUE TITLE
RPI 2 can't boot with out the pico ups installed?

### ISSUE THREAD

**Issue by RTLflat** [ef-gy/rpi-ups-pico#5]
discovered on firmware 0x53. attempted to boot several times. i can see boot status scrolling through startup and then it scrolls through (stopping) like a regular shutdown. removed /sbin files picod and pico-i2c and changed values in /etc/rc.local back to calling pimodules scripts. 

booted with no problem with or without pico. flashed firmware to new (1/26/16) firmware 0x59 and replaced scripts in case they had been updated. booted with or without pico. i edited /etc/rc.local and reinstalled picod scripts. boots with pico installed. starts to boot then shuts down every time without the pico.

**Comment by EffinMaggie** [comment]
Ah, that would make sense. GPIO 27 is presumably LOW by default. It's instead HIGH when the PIco is installed and then turns LOW when the device is supposed to shut down.

The -n flag to picod would prevent that, but it'd lose the shutdown feature altogether.

IIRC the Python script sets up the pin as a pull-up, which fixes that, but I can fix that in the daemon as well. Expect an update come weekend time :).

**Comment by EffinMaggie** [comment]
That last commit ought to have fixed this :).
